import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// SHADCN THEME
import { ThemeProvider } from "@/components/theme/theme-provider"

// COMPONENTS
import Navbar from "@/components/navbar/navbar";



const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "NSG Customer Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
